name: storydeck
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  # UI
  animations:
  bottom_navy_bar: ^6.0.0
  # State, Persitance & DI
  get_it:
  flutter_bloc:
  shared_preferences:
  # Utility
  freezed_annotation:

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  freezed:
  flutter_launcher_icons:

flutter:
  uses-material-design: true
  fonts:
    - family: Nunito
      fonts:
        - asset: fonts/Nunito-Regular.ttf
        - asset: fonts/Nunito-Light.ttf
          weight: 300
        - asset: fonts/Nunito-SemiBold.ttf
          weight: 600

flutter_icons:
  android: ic_launcher
  ios: true
  image_path: assets/icons/icon.png
